// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS8T5voHU_bam5GCQIELBbWirb9bCZZOA',
    appId: '1:331227905050:web:f8a2de1264204fdfac25a3',
    messagingSenderId: '331227905050',
    projectId: 'medic-app-1705e',
    authDomain: 'medic-app-1705e.firebaseapp.com',
    databaseURL: 'https://medic-app-1705e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medic-app-1705e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfpTuRr7lzjUlHF1LEk15rc6NIo2gP4yg',
    appId: '1:331227905050:android:5a932bde79897864ac25a3',
    messagingSenderId: '331227905050',
    projectId: 'medic-app-1705e',
    databaseURL: 'https://medic-app-1705e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medic-app-1705e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl4XJOX8i5VDksdljIUnWPnq_KmYIAs3U',
    appId: '1:331227905050:ios:5bd045a0c560ad30ac25a3',
    messagingSenderId: '331227905050',
    projectId: 'medic-app-1705e',
    databaseURL: 'https://medic-app-1705e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medic-app-1705e.appspot.com',
    iosClientId: '331227905050-4ic9ko5figfo60lk027vkuibbqt1ok6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl4XJOX8i5VDksdljIUnWPnq_KmYIAs3U',
    appId: '1:331227905050:ios:5bd045a0c560ad30ac25a3',
    messagingSenderId: '331227905050',
    projectId: 'medic-app-1705e',
    databaseURL: 'https://medic-app-1705e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medic-app-1705e.appspot.com',
    iosClientId: '331227905050-4ic9ko5figfo60lk027vkuibbqt1ok6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalSystem',
  );
}
